

import { TTypeOfTestsAndDescription } from "../tests/tests.schema";
import { TPGSyllabus } from "./global-types";



export const typeOfTestsAndDescriptionData: TTypeOfTestsAndDescription[] = [
    {
        type: 'MODEL',
        description: 'Mock test to simulate real exam conditions.',
        icon: '📊'
    },
    {
        type: 'SUBJECT_WISE',
        description: 'Test focused on a specific subject.',
        icon: '📚'
    },
    {
        type: 'CHAPTER_WISE',
        description: 'Test focused on specific chapters.',
        icon: '📖'
    },
    {
        type: 'TOPIC_WISE',
        description: 'Test focused on a particular topic.',
        icon: '📑'
    },
    {
        type: 'CUSTOM',
        description: 'Custom test created by the user.',
        icon: '🛠️'
    },
    {
        type: 'UNIT_WISE',
        description: 'Test focused on a specific unit.',
        icon: '🗂️'
    },
    {
        type: 'DIFFICULTY_BASED',
        description: 'Test based on difficulty level.',
        icon: '⚖️'
    },
    {
        type: 'RANDOM',
        description: 'Randomly selected questions for variety.',
        icon: '🎲'
    },
    {
        type: 'FLASH',
        description: 'Quick test with fast results.',
        icon: '⚡'
    },
    {
        type: 'AI_GENERATED',
        description: 'AI-generated test tailored to your needs.',
        icon: '🤖'
    },
    {
        type: 'PERFORMANCE_ANALYZER',
        description: 'Test designed to assess performance.',
        icon: '📈'
    },
    {
        type: 'PBQ_BASED',
        description: 'Test focused on practical-based questions (PBQ).',
        icon: '🧩'
    },
    {
        type: 'THEORY_BASED',
        description: 'Test focused on theoretical questions.',
        icon: '📜'
    },
    {
        type: 'REVISION',
        description: 'Test for reviewing learned material.',
        icon: '🔄'
    },
    {
        type: 'RETAKE',
        description: 'Test retake for improving previous scores.',
        icon: '🔁'
    }
];


export const PG_SYLLABUS: TPGSyllabus = {
    "anatomy": {
        "marks": 12,
        "topics": [
            "embryology",
            "histology",
            "osteology",
            "neuro_anatomy",
            "head",
            "neck",
            "back_region",
            "thorax",
            "abdomen",
            "pelvis_and_perineum",
            "lower_limb"
        ]
    },
    "physiology": {
        "marks": 12,
        "topics": [
            "homeostasis",
            "cell_functions",
            "genetic_control",
            "substance_transport",
            "membrane_potentials",
            "skeletal_muscle",
            "neuromuscular_transmission",
            "smooth_muscle",
            "cardiac_muscle",
            "heart_rhythm",
            "electrocardiogram",
            "cardiac_interpretation",
            "arrhythmias",
            "circulation_overview",
            "vascular_functions",
            "microcirculation",
            "blood_flow_control",
            "nervous_system",
            "kidney_regulation",
            "cardiac_output",
            "exercise_circulation",
            "cardiac_failure",
            "heart_defects",
            "circulatory_shock",
            "body_fluids",
            "urinary_system",
            "glomerular_filtration",
            "renal_reabsorption",
            "urine_regulation",
            "electrolyte_regulation",
            "acid-base_regulation",
            "diuretics",
            "blood_cells",
            "infection_resistance",
            "blood_types",
            "hemostasis",
            "pulmonary_ventilation",
            "pulmonary_circulation",
            "gas_exchange",
            "oxygen_transport",
            "respiration_regulation",
            "respiratory_insufficiency",
            "aviation_physiology",
            "diving_physiology",
            "gi_function",
            "food_propulsion",
            "gi_secretions",
            "digestion",
            "gi_disorders",
            "carbohydrate_metabolism",
            "lipid_metabolism",
            "protein_metabolism",
            "liver_functions",
            "feeding_regulation",
            "metabolic_rate",
            "temperature_regulation",
            "endocrinology",
            "hormonal_regulation",
            "pregnancy_lactation",
            "neonatal_physiology",
            "sports_physiology"
        ]
    },
    "biochemistry": {
        "marks": 8,
        "topics": [
            "carbohydrates",
            "fatty_acids",
            "cholesterol_and_lipoproteins",
            "amino_acid_metabolism",
            "citric_acid_cycle",
            "biological_oxidation_and_electron_transport_chain",
            "heme_synthesis_and_hemoglobin",
            "clinical_enzymology_and_biomarkers",
            "regulation_of_blood_glucose",
            "liver_function_tests",
            "gastric_function_tests",
            "kidney_function_tests",
            "plasma_proteins",
            "acid_base_balance",
            "electrolyte_and_water_balance",
            "body_fluids",
            "metabolic_diseases",
            "free_radicals_and_antioxidants",
            "vitamins",
            "mineral",
            "energy_and_nutrition",
            "xenobiotics",
            "environmental_pollution",
            "heavy_metal_poison",
            "genetics",
            "gene_therapy",
            "molecular_diagnostics_and_genetic_techniques",
            "hormones_general",
            "hypothalamic_and_pituitary_hormones",
            "steroid_hormones",
            "thyroid_hormones",
            "gut_hormones",
            "immunochemistry",
            "biochemistry_of_aids_and_hiv",
            "biochemistry_of_cancer",
            "tissue_proteins",
            "applications_of_isotopes_in_medicine",
            "signal_molecules_and_growth_factors"
        ]
    },
    "pathology": {
        "marks": 10,
        "topics": [
            "hemodynamic_disorders",
            "immune_diseases",
            "neoplasia",
            "genetic_diseases",
            "nutritional_diseases",
            "infectious_pathology",
            "blood_vessels",
            "heart",
            "liver_biliary",
            "pancreas",
            "male_genital",
            "female_genital",
            "endocrine_system",
            "bone_tumors",
            "nerves_muscles",
            "central_nervous_system",
            "hematopoietic_system",
            "lung",
            "kidney",
            "gastrointestinal_tract",
            "skin"
        ]
        

    },
    "pharmacology": {
        "marks": 10,
        "topics": [
            "principles",
            "drug_administration",
            "pharmacokinetics",
            "pharmacodynamics",
            "clinical_pharmacology",
            "adverse_effects",
            "autonomic_system",
            "cholinergic_drugs",
            "anticholinergic_drugs",
            "adrenergic_drugs",
            "antiadrenergic_drugs",
            "antihistamines",
            "serotonin_drugs",
            "prostaglandins",
            "antiinflammatory_drugs",
            "antirheumatic_drugs",
            "cough_drugs",
            "pituitary_hormones",
            "thyroid_hormones",
            "antidiabetic_drugs",
            "corticosteroids",
            "androgens",
            "estrogens",
            "oxytocin",
            "calcium_balance",
            "muscle_relaxants",
            "local_anaesthetics",
            "general_anaesthetics",
            "alcohols",
            "sedatives",
            "antiepileptics",
            "antiparkinsonian",
            "antipsychotics",
            "antidepressants",
            "opioid_drugs",
            "stimulants",
            "cardiac_drugs",
            "renin_system",
            "nitric_oxide",
            "glycosides",
            "antiarrhythmics",
            "antianginals",
            "antihypertensives",
            "urine_formation",
            "diuretics",
            "antidiuretics",
            "erythropoietin",
            "coagulation_drugs",
            "hypolipidemics",
            "peptic_ulcer_drugs",
            "antiemetics",
            "laxatives",
            "antimicrobials",
            "sulfonamides",
            "beta_lactams",
            "tetracyclines",
            "aminoglycosides",
            "macrolides",
            "antituberculars",
            "antileprotic",
            "antifungals",
            "antivirals",
            "antimalarials",
            "antiamoebics",
            "anthelmintics",
            "anticancer",
            "immunosuppressants",
            "topical_drugs",
            "antiseptics",
            "chelating_agents",
            "vitamins",
            "vaccines",
            "drug_interactions",
        ]
    },
    "microbiology": {
        "marks": 8,
        "topics": [
            "bacterial_taxonomy",
            "bacterial_morphology",
            "sterilization",
            "culture_methods",
            "bacterial_identification",
            "bacterial_genetics",
            "antimicrobial_agents",
            "pathogenicity",
            "immunity",
            "antigens",
            "antibodies",
            "immune_reactions",
            "complement_system",
            "immune_structure",
            "immune_responses",
            "hypersensitivity",
            "autoimmunity",
            "immunodeficiencies",
            "transplant_immunology",
            "immunohematology",
            "staphylococcus",
            "streptococcus",
            "neisseria",
            "corynebacterium",
            "bacillus",
            "anaerobes",
            "mycobacteria",
            "gram_positive_bacilli",
            "enterobacteriaceae",
            "vibrio",
            "pseudomonas",
            "haemophilus",
            "bordetella",
            "brucella",
            "gram_negative_bacilli",
            "spirochetes",
            "rickettsiae",
            "chlamydiae",
            "mycoplasma",
            "viral_properties",
            "herpesviruses",
            "dna_viruses",
            "myxoviruses",
            "picornaviruses",
            "arboviruses",
            "rhabdoviruses",
            "retroviruses",
            "rna_viruses",
            "hepatitis",
            "oncogenic_viruses",
            "mycology",
            "microbial_flora",
            "clinical_microbiology",
            "hospital_infections",
            "waste_management",
            "food_bacteriology",
            "emerging_infections",
            "bioterrorism",
            "laboratory_infections",
            "zoonosis"
        ]
    },
    "community_medicine": {
        "marks": 10,
        "topics": [
            "covid_19",
            "recent_updates_2021",
            "epidemiology",
            "vaccines_and_cold_chain",
            "health_and_disease",
            "screening_of_disease",
            "demography",
            "nutrition_and_health",
            "social_sciences_and_health",
            "environment_and_health",
            "international_health",
            "health_education_and_communication",
            "family_planning",
            "communicable_and_non_communicable_disease",
            "allied_health_disciplines",
            "health_planning_and_management",
            "biostatistics",
            "clinical_essentials"
        ]
    },
    "ent": {
        "marks": 10,
        "topics": [
            "anatomy_of_ear",
            "physiology_of_ear",
            "audiology_and_acoustics",
            "assessment_of_hearing",
            "hearing_loss",
            "assessment_of_vestibular_functions",
            "disorders_of_vestibular_system",
            "diseases_of_external_ear",
            "eustachian_tube_and_its_disorders",
            "disorders_of_middle_ear",
            "cholesteatoma_and_chronic_otitis_media",
            "complications_of_suppurative_otitis_media",
            "otosclerosis",
            "facial_nerve_and_disorders",
            "ménière’s_disease",
            "tumours_of_external_ear",
            "tumours_of_middle_ear_and_mastoid",
            "acoustic_neuroma",
            "the_deaf_child",
            "rehabilitation_of_the_hearing_impaired",
            "otalgia_earache",
            "tinnitus",
            "anatomy_of_nose",
            "physiology_of_nose",
            "diseases_of_external_nose_and_nasal_vestibule",
            "nasal_septum_and_its_diseases",
            "rhinitis",
            "granulomatous_diseases_of_nose",
            "miscellaneous_disorders_of_nasal_cavity",
            "allergic_rhinitis",
            "vnonallergic_rhinitis",
            "nasal_polypi",
            "epistaxis",
            "trauma_to_the_face",
            "paranasal_sinuses",
            "acute_rhinosinusitis",
            "chronic_rhinosinusitis",
            "complications_of_sinusitis",
            "neoplasms_of_nasal_cavity",
            "neoplasms_of_paranasal_sinuses",
            "proptosis",
            "anatomy_of_oral_cavity",
            "common_disorders_of_oral_cavity",
            "tumours_of_oral_cavity",
            "disorders_of_salivary_glands",
            "anatomy_and_physiology_of_pharynx",
            "inflammations_of_nasopharynx",
            "tumours_of_nasopharynx",
            "pharyngitis",
            "tonsillitis",
            "head_and_neck_infections",
            "tumours_of_oropharynx",
            "tumours_of_the_hypopharynx",
            "snoring_and_sleep_apnoea",
            "anatomy_and_physiology_of_larynx",
            "laryngotracheal_trauma",
            "inflammations_of_larynx",
            "congenital_lesions_of_larynx",
            "laryngeal_paralysis",
            "benign_tumours_of_larynx",
            "cancer_larynx",
            "voice_and_speech_disorders",
            "tracheostomy",
            "foreign_bodies_of_air_passages",
            "thyroid_gland_and_its_disorders",
            "anatomy_and_physiology_of_oesophagus",
            "disorders_of_oesophagus",
            "dysphagia",
            "foreign_bodies_of_food_passage",
            "laser_surgery",
            "coblation",
            "radiofrequency_surgery",
            "hyperbaric_oxygen_therapy",
            "cryosurgery",
            "radiotherapy_and_chemotherapy",
            "hiv_infection_aids_and_ent_manifestations",
            "clinical_methods_in_ent",
            "neck_masses",
            "myringotomy_syn_tympanostomy",
            "ear_surgery_and_approaches",
            "cortical_mastoidectomy",
            "radical_mastoidectomy",
            "modified_radical_mastoidectomy",
            "myringoplasty",
            "antral_lavage",
            "intranasal_inferior_meatal_antrostomy",
            "antrostomy_operation",
            "smr_operation",
            "septoplasty",
            "diagnostic_nasal_endoscopy",
            "endoscopic_sinus_surgery",
            "direct_laryngoscopy",
            "bronchoscopy",
            "oesophagoscopy",
            "tonsillectomy",
            "adenoidectomy",
            "imaging_techniques_in_ent",
            "instruments"
        ]
    },
    "opthalmology": {
        "marks": 7,
        "topics": [
            "anatomy_and_development_of_eye",
            "physiology_of_eye_and_vision",
            "elementary_and_physiological_optics",
            "errors_of_refraction_and_accommodation",
            "diseases_of_conjunctiva",
            "diseases_of_corna",
            "diseases_of_sclera",
            "diseases_of_uvreal_tract",
            "diseases_of_lens",
            "glaucoma",
            "diseases_of_vitreous",
            "diseases_of_retina",
            "neuro_ophthalmology",
            "disorders_of_ocular_motility",
            "disorders_of_eyelids",
            "diseases_of_lacrimal_apparatus",
            "diseases_of_orbit",
            "ocular_injuries",
            "ocular_pharmacology",
            "lasers_in_ophthalmology",
            "cryotherapy_in_ophthalmology",
            "systemic_ophthalmology",
            "community_ophthalmology",
            "clinical_methods_in_ophthalmology",
            "clinical_ophthalmic_cases",
            "darkroom_procedures",
            "ophthalmic_instruments",
            "operatve_ophthalmology"
        ]
    },
    "obg": {
        "marks": 12,
        "topics": [
            "female_anatomy",
            "reproductive_fundamentals",
            "placenta_membranes",
            "the_fetus",
            "pregnancy_changes",
            "reproductive_endocrinology",
            "pregnancy_diagnosis",
            "in_utero_fetus",
            "fetal_skull_pelvis",
            "antenatal_care",
            "fetal_wellbeing",
            "genetic_counseling",
            "normal_labor",
            "normal_puerperium",
            "nausea_vomiting",
            "early_pregnancy_hemorrhage",
            "multiple_pregnancy",
            "hypertensive_disorders",
            "antepartum_hemorrhage",
            "complications_of_pregnancy",
            "gynecological_disorders",
            "preterm_labor",
            "contracted_pelvis",
            "abnormal_uterine_action",
            "complicated_labor",
            "third_stage_complications",
            "birth_canal_injuries",
            "puerperium_abnormalities",
            "newborn_infant",
            "low_birth_weight",
            "fetal_diseases",
            "obstetric_pharmacotherapy",
            "labor_induction",
            "population_control",
            "operative_obstetrics",
            "safe_motherhood",
            "pelvic_organs_anatomy",
            "pelvic_innervation",
            "genital_development",
            "genital_malformations",
            "puberty",
            "menopause",
            "reproductive_neuroendocrinology",
            "menstruation",
            "gynecological_examination",
            "imaging_in_gynecology",
            "pelvic_infection",
            "std",
            "pelvic_infections",
            "dysmenorrhea",
            "uterine_bleeding",
            "uterine_displacement",
            "infertility",
            "benign_vulva_lesions",
            "benign_cervix_lesions",
            "benign_uterine_lesions",
            "benign_ovary_lesions",
            "endometriosis",
            "premalignant_lesions",
            "genital_malignancy",
            "urinary_issues",
            "genitourinary_fistula",
            "genital_injuries",
            "sexual_development_disorders",
            "amenorrhea",
            "contraception",
            "radiation_therapy",
            "gynecological_hormones",
            "gynecological_problems",
            "special_topics",
            "operative_gynecology",
            "endoscopic_surgery",
            "current_topics",
            "practical_gynecology"
        ]
    },
    "forensic": {
        "marks": 5,
        "topics": [
            "forensic_traumatology",
            "legal_system_and_medical_jurisprudence",
            "violent_asphyxia_deaths",
            "forensic_thanatology_and_forensic_identity",
            "sexual_jurisprudence",
            "forensic_toxicology",
            "starvation_deaths",
            "forensic_psychiatry"
        ]
    },
    "paediatrics": {
        "marks": 12,
        "topics": [
            "introduction_to_pediatrics",
            "growth",
            "development",
            "developmental_and_behavioral_disorders",
            "adolescent_health_and_development",
            "fluid_and_electrolyte_disturbances",
            "nutrition",
            "micronutrients_in_health_and_disease",
            "newborn_infants",
            "immunization_and_immunodeficiency",
            "infections_and_infestations",
            "diseases_of_liver",
            "diseases_of_gastrointestinal_system",
            "hematological_disorders",
            "otorhinolaryngology",
            "disorders_of_respiratory_system",
            "disorders_of_cardiovascular_system",
            "disorders_of_kidney_and_urinary_tract",
            "endocrine_and_metabolic_disorders",
            "diseases_of_central_nervous_system",
            "neuromuscular_disorders",
            "childhood_malignancies",
            "rheumatological_disorders",
            "genetic_disorders",
            "inborn_errors_of_metabolism",
            "ophthalmic_disorders",
            "skin_disorders",
            "poisonings_injuries_and_accidents",
            "pediatric_critical_care",
            "important_medical_procedures",
            "rational_drug_therapy",
            "imnci",
            "rights_of_children"
        ]
    },
    "surgery": {
        "marks": 18,
        "topics": [
            "metabolic_response_to_injury",
            "shock,_haemorrhage_and_transfusion",
            "wound_healing_and_tissue_repair",
            "tissue_engineering_and_regenerative_therapies",
            "surgical_infection",
            "tropical_infections_and_infestations",
            "basic_surgical_skills",
            "diagnostic_imaging",
            "gastrointestinal_endoscopy",
            "principles_of_minimal_access_surgery",
            "tissue_and_molecular_diagnosis",
            "principles_of_oncology",
            "surgical_audit_and_research",
            "ethics_and_law",
            "patient_safety",
            "global_health_and_surgery",
            "paediatric_surgery",
            "neonatal_surgery",
            "trauma_in_children",
            "paediatric_urology",
            "preoperative_care",
            "day_case_surgery",
            "anaesthesia_and_pain_relief",
            "postoperative_care",
            "nutrition_and_fluid_therapy",
            "introduction_to_trauma",
            "assessment_and_management_of_severe_trauma",
            "traumatic_brain_injury",
            "torso_and_pelvic_trauma",
            "the_neck_and_spine",
            "maxillofacial_trauma",
            "extremity_trauma",
            "disaster_surgery",
            "conflict_surgery",
            "history_taking_and_examination_in_msk_disease",
            "sports_medicine_and_sports_injuries",
            "the_spine",
            "the_upper_limb",
            "the_hip",
            "the_knee",
            "the_foot_and_ankle",
            "musculoskeletal_tumours",
            "infection_of_bones_and_joints",
            "paediatric_orthopaedics",
            "skin_and_subcutaneous_tissue",
            "burns",
            "plastic_and_reconstructive_surgery",
            "cranial_neurosurgery",
            "the_eye_and_orbit",
            "developmental_abnormalities_of_the_face_mouth_and_jaws",
            "the_ear,_nose_and_sinuses",
            "the_pharynx_larynx_and_neck",
            "oral_cavity_cancer",
            "disorders_of_the_salivary_glands",
            "the_thyroid_gland",
            "the_parathyroid_glands",
            "abdominal_endocrine_disorders",
            "the_breast",
            "cardiac_surgery",
            "the_thorax",
            "arterial_disorders",
            "venous_disorders",
            "lymphatic_disorders",
            "history_and_examination_of_the_abdomen",
            "hernia_and_umbilicus",
            "Gi_viscera",
            "the_oesophagus",
            "the_stomach_and_duodenum",
            "bariatric_and_metabolic_surgery",
            "the_liver",
            "the_spleen",
            "the_gallbladder_and_bile_ducts",
            "the_pancreas",
            "functional_disorders_of_the_intestine",
            "the_small_intestine",
            "inflammatory_bowel_disease",
            "the_vermiform_appendix",
            "the_large_intestine",
            "intestinal_obstruction",
            "the_rectum",
            "the_anus_and_anal_canal",
            "urinary_symptoms_and_investigations",
            "the_kidney_and_ureter",
            "the_urinary_bladder",
            "the_prostate_and_seminal_vesicles",
            "the_urethra_and_penis",
            "the_testis_and_scrotum",
            "gynaecology",
            "kidney_transplantation",
            "liver_transplantation",
            "pancreas_transplantation",
            "intestinal_and_multivisceral_transplantation",
            "heart_and_lung_transplantation"
        ]
    },
    "medicine": {
        "marks": 18,
        "topics": [
            "clinical_decision",
            "therapeutics_prescribing",
            "clinical_genetics",
            "clinical_immunology",
            "population_health",
            "infectious_disease_principles",
            "poisoning",
            "envenomation",
            "environmental_medicine",
            "acute_medicine",
            "infectious_diseases",
            "hiv_aids",
            "sti",
            "clinical_biochemistry",
            "nephrology",
            "urology",
            "cardiology",
            "respiratory_medicine",
            "endocrinology",
            "nutritional_factors",
            "diabetes",
            "gastroenterology",
            "hepatology",
            "haematology",
            "transfusion_medicine",
            "rheumatology",
            "neurology",
            "stroke_medicine",
            "ophthalmology",
            "psychiatry",
            "dermatology",
            "maternal_medicine",
            "adolescent_medicine",
            "ageing_disease",
            "oncology",
            "palliative_care",
            "laboratory_ranges"
        ]
    },
    "radiology": {
        "marks": 7,
        "topics": [
            "x-rays",
            "ct_scan",
            "magnetic_resonance_imaging",
            "ultrasound",
            "thumb_rules",
            "angiography_dsa_interventional_radiology",
            "contrast_agents",
            "gastrointestinal_radiology",
            "hepatobiliary_radiology",
            "pancreatic_radiology",
            "genitourinary_radiology",
            "neuroradiology",
            "musculoskeletal_radiology",
            "women_imaging",
            "cardiovascular_radiology",
            "clinical_essentials",
            "respiratory_radiology",
            "nuclear_medicine",
            "radiotherapy",
            "radiological_anatomy"
        ]
    },
    "emergency_medicine": {
        "marks": 0,
        "topics": [
            "an_approach_of_undifferentiated_patient",
            "basics_of_emergency_medicine",
            "cardiovascular_emergencies",
            "neurological_emergencies",
            "respiratory_emergencies",
            "abdominal_emergencies",
            "miscellaneous_emergencies"
        ]
    },
    "psychiatry": {
        "marks": 7,
        "topics": [
            "organic_mental_disorders",
            "personality_disorders",
            "eating_disorders",
            "sleep_disorders",
            "sexual_disorders",
            "basics_of_psychiatry",
            "schizophrenia_spectrum",
            "mood_disorders",
            "neurotic_stress_related_and_somatoform_disorders",
            "substance_related_and_addictive_disorders",
            "child_psychiatry",
            "psychoanalysis",
            "mental_health_care_act_2017"
        ]
    },
    "dermatology": {
        "marks": 7,
        "topics": [
            "introduction_to_dermatology",
            "blistering_disorders",
            "pigmentary_disorders",
            "bacterial_infections",
            "fungal_infections",
            "mycobacterial_infections",
            "viral_infections",
            "sexually_transmitted_infections",
            "papulosquamous_disorders",
            "miscellaneous_disorders"
        ]
    },
    "orthopedics": {
        "marks": 10,
        "topics": [
            "bone_and_imaging",
            "bone_and_joint_infections",
            "tuberculosis_of_bone_and_joints",
            "orthopaedics_oncology",
            "nerve_injuries",
            "general_upper_limb_traumatology",
            "spine_pelvis_lower_limb_traumatology",
            "arthritis",
            "metabolic_disorders",
            "sports_injury_and_nm_disorders",
            "pediatric_orthopedics"
        ]
    }
}
