

import { TTypeOfTestsAndDescription } from "../tests/tests.schema";
import { TPGSyllabus } from "./global-types";


  
export const typeOfTestsAndDescriptionData: TTypeOfTestsAndDescription[] = [
    {
        type: 'MODEL',
        description: 'Mock test to simulate real exam conditions.',
        icon: '📊'
    },
    {
        type: 'SUBJECT_WISE',
        description: 'Test focused on a specific subject.',
        icon: '📚'
    },
    {
        type: 'CHAPTER_WISE',
        description: 'Test focused on specific chapters.',
        icon: '📖'
    },
    {
        type: 'TOPIC_WISE',
        description: 'Test focused on a particular topic.',
        icon: '📑'
    },
    {
        type: 'CUSTOM',
        description: 'Custom test created by the user.',
        icon: '🛠️'
    },
    {
        type: 'UNIT_WISE',
        description: 'Test focused on a specific unit.',
        icon: '🗂️'
    },
    {
        type: 'DIFFICULTY_BASED',
        description: 'Test based on difficulty level.',
        icon: '⚖️'
    },
    {
        type: 'RANDOM',
        description: 'Randomly selected questions for variety.',
        icon: '🎲'
    },
    {
        type: 'FLASH',
        description: 'Quick test with fast results.',
        icon: '⚡'
    },
    {
        type: 'AI_GENERATED',
        description: 'AI-generated test tailored to your needs.',
        icon: '🤖'
    },
    {
        type: 'PERFORMANCE_ANALYZER',
        description: 'Test designed to assess performance.',
        icon: '📈'
    },
    {
        type: 'PBQ_BASED',
        description: 'Test focused on practical-based questions (PBQ).',
        icon: '🧩'
    },
    {
        type: 'THEORY_BASED',
        description: 'Test focused on theoretical questions.',
        icon: '📜'
    },
    {
        type: 'REVISION',
        description: 'Test for reviewing learned material.',
        icon: '🔄'
    },
    {
        type: 'RETAKE',
        description: 'Test retake for improving previous scores.',
        icon: '🔁'
    }
];

  



export const PG_SYLLABUS: TPGSyllabus = {
    "anatomy": {
        "marks": 12,
        "topics": [
            "embryology",
            "histology",
            "osteology_and_arthrology",
            "neuro_anatomy",
            "head_and_neck",
            "back_region",
            "thorax",
            "abdomen",
            "pelvis_and_perineum",
            "lower_limb"
        ]
    },
    "physiology": {
        "marks": 12,
        "topics": [
            "functional_organization_of_the_human_body_and_control_of_the_internal_environment",
            "the_cell_and_its_functions",
            "genetic_control_of_protein_synthesis_cell_function_and_cell_reproduction",
            "transport_of_substances_through_cell_membranes",
            "membrane_potentials_and_action_potentials",
            "contraction_of_skeletal_muscle",
            "excitation_of_skeletal_muscle_neuromuscular_transmission_and_excitation_contraction_coupling",
            "excitation_and_contraction_of_smooth_muscle",
            "cardiac_muscle_the_heart_as_a_pump_and_function_of_the_heart_valves",
            "rhythmical_excitation_of_the_heart",
            "the_normal_electrocardiogram",
            "electrocardiographic_interpretation_of_cardiac_muscle_and_coronary_blood_flow_abnormalities_vectorial_analysis",
            "cardiac_arrhythmias_and_their_electrocardiographic_interpretation",
            "overview_of_the_circulation_biophysics_of_pressure_flow_and_resistance",
            "vascular_distensibility_and_functions_of_the_arterial_and_venous_systems",
            "the_microcirculation_and_lymphatic_system_capillary_fluid_exchange_interstitial_fluid_and_lymph_flow",
            "local_and_humoral_control_of_tissue_blood_flow",
            "nervous_regulation_of_the_circulation_and_rapid_control_of_arterial_pressure",
            "role_of_the_kidneys_in_long_term_control_of_arterial_pressure_and_in_hypertension_the_integrated_system_for_arterial_pressure_regulation",
            "cardiac_output_venous_return_and_their_regulation",
            "muscle_blood_flow_and_cardiac_output_during_exercise_the_coronary_circulation_and_ischemic_heart_disease",
            "cardiac_failure",
            "heart_valves_and_heart_sounds_valvular_and_congenital_heart_defects",
            "circulatory_shock_and_its_treatment",
            "the_body_fluid_compartments_extracellular_and_intracellular_fluids_edema",
            "the_urinary_system_functional_anatomy_and_urine_formation_by_the_kidneys",
            "glomerular_filtration_renal_blood_flow_and_their_control",
            "renal_tubular_reabsorption_and_secretion",
            "urine_concentration_and_dilution_regulation_of_extracellular_fluid_osmolarity_and_sodium_concentration",
            "renal_regulation_of_potassium_calcium_phosphate_and_magnesium_integration_of_renal_mechanisms_for_control_of_blood_volume_and_extracellular_fluid_volume",
            "acid_base_regulation",
            "diuretics_kidney_diseases",
            "red_blood_cells_anemia_and_polycythemia",
            "resistance_of_the_body_to_infection_i_leukocytes_granulocytes_the_monocyte_macrophage_system_and_inflammation",
            "resistance_of_the_body_to_infection_ii_immunity_and_allergy",
            "blood_types_transfusion_tissue_and_organ_transplantation",
            "hemostasis_and_blood_coagulation",
            "pulmonary_ventilation",
            "pulmonary_circulation_pulmonary_edema_pleural_fluid",
            "principles_of_gas_exchange_diffusion_of_oxygen_and_carbon_dioxide_through_the_respiratory_membrane",
            "transport_of_oxygen_and_carbon_dioxide_in_blood_and_tissue_fluids",
            "regulation_of_respiration",
            "respiratory_insufficiency_pathophysiology_diagnosis_oxygen_therapy",
            "aviation_high_altitude_and_space_physiology",
            "physiology_of_deep_sea_diving_and_other_hyperbaric_conditions",
            "organization_of_the_nervous_system_basic_functions_of_synapses_and_neurotransmitters",
            "sensory_receptors_neuronal_circuits_for_processing_information",
            "somatic_sensations_i_general_organization_the_tactile_and_position_senses",
            "somatic_sensations_ii_pain_headache_and_thermal_sensations",
            "the_eye_i_optics_of_vision",
            "the_eye_ii_receptor_and_neural_function_of_the_retina",
            "the_eye_iii_central_neurophysiology_of_vision",
            "the_sense_of_hearing",
            "the_chemical_senses_taste_and_smell",
            "motor_functions_of_the_spinal_cord_the_cord_reflexes",
            "cortical_and_brain_stem_control_of_motor_function",
            "contributions_of_the_cerebellum_and_basal_ganglia_to_overall_motor_control",
            "cerebral_cortex_intellectual_functions_of_the_brain_learning_and_memory",
            "behavioral_and_motivational_mechanisms_of_the_brain_the_limbic_system_and_the_hypothalamus",
            "states_of_brain_activity_sleep_brain_waves_epilepsy_psychoses_and_dementia",
            "the_autonomic_nervous_system_and_the_adrenal_medulla",
            "cerebral_blood_flow_cerebrospinal_fluid_and_brain_metabolism",
            "general_principles_of_gastrointestinal_function_motility_nervous_control_and_blood_circulation",
            "propulsion_and_mixing_of_food_in_the_alimentary_tract",
            "secretory_functions_of_the_alimentary_tract",
            "digestion_and_absorption_in_the_gastrointestinal_tract",
            "physiology_of_gastrointestinal_disorders",
            "metabolism_of_carbohydrates_and_formation_of_adenosine_triphosphate",
            "lipid_metabolism",
            "protein_metabolism",
            "the_liver_as_an_organ",
            "dietary_balances_regulation_of_feeding_obesity_and_starvation_vitamins_and_minerals",
            "energetics_and_metabolic_rate",
            "body_temperature_regulation_and_fever",
            "introduction_to_endocrinology",
            "pituitary_hormones_and_their_control_by_the_hypothalamus",
            "thyroid_metabolic_hormones",
            "adenocortical_hormones",
            "insulin_glucagon_and_diabetes_mellitus",
            "parathyroid_hormone_calcitonin_calcium_and_phosphate_metabolism_vitamin_d_bone_and_teeth",
            "reproductive_and_hormonal_functions_of_the_male_and_function_of_the_pineal_gland",
            "female_physiology_before_pregnancy_and_female_hormones",
            "pregnancy_and_lactation",
            "fetal_and_neonatal_physiology",
            "sports_physiology"
        ]

    },
    "biochemistry": {
        "marks": 8,
        "topics": [
            "metabolic_pathways_of_other_carbohydrates",
            "metabolism_of_fatty_acids",
            "cholesterol_and_lipoproteins",
            "mcfa_pufa_prostaglandins_and_compound_lipids",
            "general_amino_acid_metabolism",
            "simple_hydroxy_and_sulfur_containing_amino_acids",
            "acidic_basic_and_branches_chain_amino_acids",
            "aromatic_amino_acids_and_amino_acidurias",
            "citric_acid_cycle",
            "biological_oxidation_and_electron_transport_chain",
            "heme_synthesis_and_breakdown",
            "hemoglobin_structure_and_transport",
            "clinical_enzymology_and_biomarkers",
            "regulation_of_blood_glucose_and_diabetes_mellitus",
            "hyperlipidemias_and_cardiovascular_diseases",
            "liver_and_gastric_function_tests",
            "kidney_function_tests",
            "plasma_proteins",
            "acid_base_balance_and_ph",
            "electrolyte_and_water_balance",
            "body_fluids",
            "metabolic_diseases",
            "free_radicals_and_antioxidants",
            "clinical_laboratory_quality_control",
            "general_techniques_for_separation_purification_and_quantitation",
            "fat_soluble_vitamins",
            "water_soluble_vitamins_1",
            "water_soluble_vitamins_2",
            "mineral_metabolism_and_abnormalities",
            "energy_metabolism_and_nutrition",
            "detoxification_and_biotransformation_of_xenobiotics",
            "environmental_pollution_and_heavy_metal_poison",
            "nucleotides_chemistry_and_metabolism",
            "deoxyribonucleic_acid_structure_and_replication",
            "transcription",
            "genetic_code_and_translation",
            "control_of_gene_expression",
            "recombinant_dna_technology_and_gene_therapy",
            "molecular_diagnostics_and_genetic_techniques",
            "mechanisms_of_action_of_hormones_and_signaling_molecules",
            "hypothalamic_and_pituitary_hormones",
            "steroid_hormones",
            "thyroid_hormones",
            "gut_hormones",
            "immunochemistry",
            "biochemistry_of_aids_and_hiv",
            "biochemistry_of_cancer",
            "tissue_proteins_in_health_and_disease",
            "applications_of_isotopes_in_medicine",
            "signal_molecules_and_growth_factors"
        ]

    },
    "pathology": {
        "marks": 10,
        "topics": [
            "hemodynamic_disorders_thromboembolism_and_shock",
            "diseases_of_the_immune_system",
            "neoplasia",
            "genetic_and_pediatric_diseases",
            "environmental_and_nutritional_diseases",
            "general_pathology_of_infectious_diseases",
            "blood_vessels",
            "heart",
            "liver_gallbladder_and_biliary_tract",
            "pancreas",
            "male_genital_system_and_lower_urinary_tract",
            "female_genital_system_and_breast",
            "endocrine_system",
            "bones_joints_and_soft_tissue_tumors",
            "peripheral_nerves_and_muscles",
            "central_nervous_system",
            "hematopoietic_and_lymphoid_systems",
            "lung",
            "kidney_and_its_collecting_system",
            "oral_cavity_and_gastrointestinal_tract",
            "skin"
        ]

    },
    "pharmacology": {
        "marks": 10,
        "topics": [
            "general_pharmacological_principles",
            "introduction_routes_of_drug_administration",
            "pharmacokinetics_membrane_transport_absorption_and_distribution_of_drugs",
            "pharmacokinetics_metabolism_and_excretion_of_drugs_kinetics_of_elimination",
            "pharmacodynamics_mechanism_of_drug_action_receptor_pharmacology",
            "aspects_of_pharmacotherapy_clinical_pharmacology_and_drug_development",
            "adverse_drug_effects",
            "autonomic_nervous_system_general_considerations",
            "cholinergic_transmission_and_cholinergic_drugs",
            "anticholinergic_drugs_and_drugs_acting_on_autonomic_ganglia",
            "adrenergic_transmission_and_adrenergic_drugs",
            "antiadrenergic_drugs_and_drugs_for_glaucoma",
            "histamine_and_antihistaminics",
            "5-hydroxytryptamine_its_antagonists_and_drug_therapy_of_migraine",
            "prostaglandins_leukotrienes_and_platelet_activating_factor",
            "nonsteroidal_antiinflammatory_drugs_and_antipyretic_analgesics",
            "antirheumatoid_and_antigout_drugs",
            "drugs_for_cough_and_bronchial_asthma",
            "anterior_pituitary_hormones",
            "thyroid_hormones_and_thyroid_inhibitors",
            "insulin_oral_antidiabetic_drugs_and_glucagon",
            "corticosteroids",
            "androgens_and_related_drugs_drugs_for_erectile_dysfunction",
            "estrogens_progestins_and_contraceptives",
            "oxytocin_and_other_drugs_acting_on_uterus",
            "hormones_and_drugs_affecting_calcium_balance",
            "skeletal_muscle_relaxants",
            "local_anaesthetics",
            "general_anaesthetics",
            "ethyl_and_methyl_alcohols",
            "sedative_hypnotics",
            "antiepileptic_drugs",
            "antiparkinsonian_drugs",
            "drugs_used_in_mental_illness_antipsychotic_and_antimanic_drugs",
            "drugs_used_in_mental_illness_antidepressant_and_antianxiety_drugs",
            "opioid_analgesics_and_antagonists",
            "cns_stimulants_and_cognition_enhancers",
            "cardiac_electrophysiological_considerations",
            "drugs_affecting_renin_angiotensin_system",
            "nitric_oxide_and_vasoactive_peptide_signal_molecules",
            "cardiac_glycosides_and_drugs_for_heart_failure",
            "antiarrhythmic_drugs",
            "antianginal_and_other_anti-ischaemic_drugs",
            "antihypertensive_drugs",
            "relevant_physiology_of_urine_formation",
            "diuretics",
            "antidiuretics",
            "haematinics_and_erythropoietin",
            "drugs_affecting_coagulation_bleeding_and_thrombosis",
            "hypolipidaemic_drugs",
            "drugs_for_peptic_ulcer_and_gastroesophageal_reflux_disease",
            "antiemetic_prokinetic_and_digestant_drugs",
            "drugs_for_constipation_and_diarrhoea",
            "antimicrobial_drugs_general_considerations",
            "sulfonamides_cotrimoxazole_and_quinolones",
            "beta-lactam_antibiotics",
            "tetracyclines_and_chloramphenicol_broad-spectrum_antibiotics",
            "aminoglycoside_antibiotics",
            "macrolide_lincosamide_glycopeptide_and_other_antibacterial_antibiotics_urinary_antiseptics",
            "antitubercular_drugs",
            "antileprotic_drugs",
            "antifungal_drugs",
            "antiviral_drugs_non-retroviral",
            "antiviral_drugs_anti-retrovirus",
            "antimalarial_drugs",
            "antiamoebic_and_other_antiprotozoal_drugs",
            "anthelmintic_drugs",
            "anticancer_drugs",
            "immunosuppressant_drugs",
            "drugs_acting_on_skin_and_mucous_membranes",
            "antiseptics_disinfectants_and_ectoparasiticides",
            "chelating_agents",
            "vitamins",
            "vaccines_antisera_and_immunoglobulins",
            "drug_interactions",
            "appendix_solution_to_problem_directed_study",
            "appendix_prescribing_in_pregnancy",
            "appendix_drugs_in_breastfeeding",
            "appendix_drugs_and_fixed_dose_combinations_banned_in_india",
            "selected_references_for_further_reading",
            "index"
        ]

    },
    "microbiology": {
        "marks": 8,
        "topics": [
            "introduction_and_bacterial_taxonomy",
            "morphology_and_physiology_of_bacteria",
            "sterilization_and_disinfection",
            "culture_media_and_culture_methods",
            "identification_of_bacteria",
            "bacterial_genetics",
            "antimicrobial_agents_antimicrobial_resistance_and_antimicrobial_susceptibility_testing",
            "microbial_pathogenicity",
            "immunity_innate_and_acquired",
            "antigen",
            "antibody",
            "antigen_antibody_reaction",
            "complement",
            "structure_of_immune_system",
            "immune_responses_cell-mediated_and_antibody-mediated",
            "hypersensitivity",
            "autoimmunity",
            "immunodeficiency_disorders",
            "transplant_and_cancer_immunology",
            "immunoprophylaxis_and_immunohematology",
            "staphylococcus",
            "streptococcus_enterococcus_and_pneumococcus",
            "neisseria_and_moraxella",
            "corynebacterium",
            "bacillus",
            "anaerobes_clostridium_and_non-sporing_anaerobes",
            "mycobacteria",
            "miscellaneous_gram_positive_bacilli",
            "enterobacteriaceae_1",
            "enterobacteriaceae_2_salmonella",
            "vibrio_and_aeromonas",
            "pseudomonas_and_other_non-fermenters",
            "haemophilus_and_hacek_group",
            "bordetella",
            "brucella",
            "miscellaneous_gram_negative_bacilli",
            "spirochetes",
            "rickettsiae_coxiella_bartonella",
            "chlamydiae",
            "mycoplasma_and_ureaplasma",
            "general_properties_of_viruses",
            "herpesviruses",
            "other_dna_viruses",
            "myxoviruses_and_rubella_virus",
            "picornaviruses",
            "arboviruses",
            "rhabdoviruses",
            "hiv_and_other_retroviruses",
            "miscellaneous_rna_viruses",
            "hepatitis_viruses",
            "oncogenic_viruses",
            "medical_mycology",
            "normal_microbial_flora_of_human_body",
            "clinical_microbiology_infective_syndromes",
            "hospital_acquired_infections",
            "biomedical_waste_management",
            "bacteriology_of_water_milk_air_and_food",
            "emerging_and_re-emerging_infections",
            "bioterrorism",
            "laboratory_acquired_infections",
            "zoonosis"
        ]

    },
    "community_medicine": {
        "marks": 10,
        "topics": [
            "covid_19",
            "recent_updates_2021",
            "epidemiology",
            "vaccines_and_cold_chain",
            "health_and_disease",
            "screening_of_disease",
            "demography",
            "nutrition_and_health",
            "social_sciences_and_health",
            "environment_and_health",
            "international_health",
            "health_education_and_communication",
            "family_planning_and_contraception",
            "communicable_and_non_communicable_disease",
            "national_health_programmes_policies_and_legislations_in_india",
            "allied_health_disciplines",
            "health_planning_and_management",
            "biostatistics",
            "clinical_essentials"
        ]
    },
    "ent": {
        "marks": 10,
        "topics": [
            "anatomy_of_ear",
            "peripheral_receptors_and_physiology_of_auditory_and_vestibular_systems",
            "audiology_and_acoustics",
            "assessment_of_hearing",
            "hearing_loss",
            "assessment_of_vestibular_functions",
            "disorders_of_vestibular_system",
            "diseases_of_external_ear",
            "eustachian_tube_and_its_disorders",
            "disorders_of_middle_ear",
            "cholesteatoma_and_chronic_otitis_media",
            "complications_of_suppurative_otitis_media",
            "otosclerosis_syn_otospongiosis",
            "facial_nerve_and_its_disorders",
            "ménière’s_disease",
            "tumours_of_external_ear",
            "tumours_of_middle_ear_and_mastoid",
            "acoustic_neuroma",
            "the_deaf_child",
            "rehabilitation_of_the_hearing_impaired",
            "otalgia_earache",
            "tinnitus",
            "anatomy_of_nose",
            "physiology_of_nose",
            "diseases_of_external_nose_and_nasal_vestibule",
            "nasal_septum_and_its_diseases",
            "acute_and_chronic_rhinitis",
            "granulomatous_diseases_of_nose",
            "miscellaneous_disorders_of_nasal_cavity",
            "allergic_rhinitis",
            "vasomotor_and_other_forms_of_nonallergic_rhinitis",
            "nasal_polypi",
            "epistaxis",
            "trauma_to_the_face",
            "anatomy_and_physiology_of_paranasal_sinuses",
            "acute_rhinosinusitis",
            "chronic_rhinosinusitis",
            "complications_of_sinusitis",
            "benign_and_malignant_neoplasms_of_nasal_cavity",
            "neoplasms_of_paranasal_sinuses",
            "proptosis",
            "anatomy_of_oral_cavity",
            "common_disorders_of_oral_cavity",
            "tumours_of_oral_cavity",
            "non_neoplastic_disorders_of_salivary_glands",
            "neoplasms_of_salivary_glands",
            "anatomy_and_physiology_of_pharynx",
            "adenoids_and_other_inflammations_of_nasopharynx",
            "tumours_of_nasopharynx",
            "acute_and_chronic_pharyngitis",
            "acute_and_chronic_tonsillitis",
            "head_and_neck_space_infections",
            "tumours_of_oropharynx",
            "tumours_of_the_hypopharynx_and_pharyngeal_pouch",
            "snoring_and_sleep_apnoea",
            "anatomy_and_physiology_of_larynx",
            "laryngotracheal_trauma",
            "acute_and_chronic_inflammations_of_larynx",
            "congenital_lesions_of_larynx_and_stridor",
            "laryngeal_paralysis",
            "benign_tumours_of_larynx",
            "cancer_larynx",
            "voice_and_speech_disorders",
            "tracheostomy_and_other_procedures_for_airway_management",
            "foreign_bodies_of_air_passages",
            "thyroid_gland_and_its_disorders",
            "anatomy_and_physiology_of_oesophagus",
            "disorders_of_oesophagus",
            "dysphagia",
            "foreign_bodies_of_food_passage",
            "laser_surgery_radiofrequency_surgery_hyperbaric_oxygen_therapy_and_coblation",
            "cryosurgery",
            "radiotherapy_in_head_and_neck_cancers",
            "chemotherapy_for_head_and_neck_cancer",
            "hiv_infection_aids_and_ent_manifestations",
            "clinical_methods_in_ent",
            "neck_masses",
            "myringotomy_syn_tympanostomy",
            "ear_surgery_and_approaches",
            "cortical_mastoidectomy",
            "radical_mastoidectomy",
            "modified_radical_mastoidectomy",
            "myringoplasty",
            "proof_puncture_syn_antral_lavage",
            "intranasal_inferior_meatal_antrostomy",
            "caldwell_luc_anterior_antrostomy_operation",
            "submucous_resection_of_nasal_septum_smr_operation",
            "septoplasty",
            "diagnostic_nasal_endoscopy",
            "endoscopic_sinus_surgery",
            "direct_laryngoscopy",
            "bronchoscopy",
            "oesophagoscopy",
            "tonsillectomy",
            "adenoidectomy",
            "some_imaging_techniques_in_ent",
            "some_memorable_nuggets_for_rapid_review",
            "instruments"
        ]
    },
    "opthalmology": {
        "marks": 7,
        "topics": [
            "anatomy_and_development_of_eye",
            "physiology_of_eye_and_vision",
            "elementary_and_physiological_optics",
            "errors_of_refraction_and_accommodation",
            "diseases_of_conjunctiva",
            "diseases_of_corna",
            "diseases_of_sclera",
            "diseases_of_uvreal_tract",
            "diseases_of_lens",
            "glaucoma",
            "diseases_of_vitreous",
            "diseases_of_retina",
            "neuro_ophthalmology",
            "disorders_of_ocular_motility",
            "disorders_of_eyelids",
            "diseases_of_lacrimal_apparatus",
            "diseases_of_orbit",
            "ocular_injuries",
            "ocular_pharmacology",
            "lasers_and_cryotherapy_in_ophthalmology",
            "systemic_ophthalmology",
            "community_ophthalmology",
            "clinical_methods_in_ophthalmology",
            "clinical_ophthalmic_cases",
            "darkroom_procedures",
            "ophthalmic_instruments_and_operatve_ophthalmology"
        ]
    },
    "obg": {
        "marks": 12,
        "topics": [
            "anatomy_of_female_reproductive_organs",
            "fundamentals_of_reproduction",
            "placenta_and_fetal_membranes",
            "the_fetus",
            "physiological_changes_during_pregnancy",
            "endocrinology_in_relation_to_reproduction",
            "diagnosis_of_pregnancy",
            "fetus_in_utero",
            "fetal_skull_and_maternal_pelvis",
            "antenatal_care_preconceptional_counseling_and_care",
            "antenatal_assessment_of_fetal_wellbeing",
            "prenatal_genetic_counseling_screening_and_diagnosis",
            "normal_labor",
            "normal_puerperium",
            "nausea_and_vomiting_in_pregnancy",
            "hemorrhage_in_early_pregnancy",
            "multiple_pregnancy_amniotic_fluid_disorders_abnormalities_of_placenta_and_cord",
            "hypertensive_disorders_in_pregnancy",
            "antepartum_hemorrhage",
            "medical_and_surgical_illnesses_complicating_pregnancy",
            "gynecological_disorders_in_pregnancy",
            "preterm_labor_and_birth_preterm_rupture_of_the_membranes_prolonged_pregnancy_intrauterine_fetal_death",
            "complicated_pregnancy",
            "contracted_pelvis",
            "abnormal_uterine_action",
            "complicated_labor_malposition_malpresentation_and_cord_prolapse",
            "prolonged_labor_obstructed_labor_dystocia_caused_by_fetal_anomalies",
            "complications_of_the_third_stage_of_labor",
            "injuries_to_the_birth_canal",
            "abnormalities_of_the_puerperium",
            "the_term_newborn_infant",
            "low_birth_weight_baby",
            "diseases_of_the_fetus_and_the_newborn",
            "pharmacotherapeutics_in_obstetrics",
            "induction_of_labor",
            "population_dynamics_and_control_of_conception",
            "operative_obstetrics",
            "safe_motherhood_epidemiology_of_obstetrics",
            "anatomy_of_the_female_pelvic_organs",
            "blood_vessels_lymphatic_drainage_and_innervation_of_pelvic_organs",
            "development_of_genital_organs_and_gonads",
            "congenital_malformation_of_female_genital_organs",
            "puberty_normal_and_abnormal",
            "menopause",
            "neuroendocrinology_in_relation_to_reproduction",
            "menstruation",
            "examination_of_a_gynecological_patient_and_the_diagnostic_procedures",
            "imaging_techniques_other_diagnostic_procedures_and_laser_in_gynecology",
            "pelvic_infection",
            "sexually_transmitted_infections",
            "infections_of_the_individual_pelvic_organ",
            "dysmenorrhea_and_other_disorders_of_menstrual_cycles",
            "abnormal_uterine_bleeding",
            "displacement_of_the_uterus",
            "infertility",
            "benign_lesions_of_the_vulva_and_vagina",
            "benign_lesions_of_the_cervix",
            "benign_lesions_of_the_uterus",
            "benign_neoplasms_of_the_ovary",
            "endometriosis_and_adenomyosis",
            "premalignant_lesions",
            "genital_malignancy",
            "urinary_problems_in_gynecology",
            "genitourinary_fistula",
            "genital_tract_injuries_and_anorectal_dysfunctions",
            "disorders_of_sexual_development",
            "amenorrhea",
            "contraception",
            "basic_principles_of_radiation_therapy_chemotherapy_immunotherapy_and_gene_therapy_in_gynecology",
            "hormones_in_gynecological_practice",
            "gynecological_problems_from_birth_to_adolescence",
            "special_topics",
            "operative_gynecology",
            "endoscopic_surgery_in_gynecology",
            "current_topics_in_gynecology",
            "practical_gynecology"
        ]

    },
    "forensic": {
        "marks": 5,
        "topics": [
            "forensic_traumatology",
            "legal_system_and_medical_jurisprudence",
            "violent_asphyxia_deaths",
            "forensic_thanatology_and_forensic_identity",
            "sexual_jurisprudence",
            "forensic_toxicology",
            "starvation_deaths",
            "forensic_psychiatry"
        ]
    },
    "paediatrics": {
        "marks": 12,
        "topics": [
            "introduction_to_pediatrics",
            "growth",
            "development",
            "developmental_and_behavioral_disorders",
            "adolescent_health_and_development",
            "fluid_and_electrolyte_disturbances",
            "nutrition",
            "micronutrients_in_health_and_disease",
            "newborn_infants",
            "immunization_and_immunodeficiency",
            "infections_and_infestations",
            "diseases_of_gastrointestinal_system_and_liver",
            "hematological_disorders",
            "otorhinolaryngology",
            "disorders_of_respiratory_system",
            "disorders_of_cardiovascular_system",
            "disorders_of_kidney_and_urinary_tract",
            "endocrine_and_metabolic_disorders",
            "diseases_of_central_nervous_system",
            "neuromuscular_disorders",
            "childhood_malignancies",
            "rheumatological_disorders",
            "genetic_disorders",
            "inborn_errors_of_metabolism",
            "ophthalmic_disorders",
            "skin_disorders",
            "poisonings_injuries_and_accidents",
            "pediatric_critical_care",
            "important_medical_procedures",
            "rational_drug_therapy",
            "integrated_management_of_neonatal_and_childhood_illness",
            "rights_of_children"
          ]          
    },
    "surgery": {
        "marks": 18,
        "topics": [
            "metabolic_response_to_injury",
            "shock,_haemorrhage_and_transfusion",
            "wound_healing_and_tissue_repair",
            "tissue_engineering_and_regenerative_therapies",
            "surgical_infection",
            "tropical_infections_and_infestations",
            "basic_surgical_skills",
            "diagnostic_imaging",
            "gastrointestinal_endoscopy",
            "principles_of_minimal_access_surgery",
            "tissue_and_molecular_diagnosis",
            "principles_of_oncology",
            "surgical_audit_and_research",
            "ethics_and_law_in_surgical_practice",
            "human_factors,_patient_safety_and_quality_improvement",
            "global_health_and_surgery",
            "paediatric_surgery",
            "neonatal_surgery",
            "trauma_in_children",
            "paediatric_urology",
            "preoperative_care_including_the_high-risk_surgical_patient",
            "day_case_surgery",
            "anaesthesia_and_pain_relief",
            "postoperative_care_including_perioperative_optimisation",
            "nutrition_and_fluid_therapy",
            "introduction_to_trauma",
            "early_assessment_and_management_of_severe_trauma",
            "traumatic_brain_injury",
            "torso_and_pelvic_trauma",
            "the_neck_and_spine",
            "maxillofacial_trauma",
            "extremity_trauma",
            "disaster_surgery",
            "conflict_surgery",
            "history_taking_and_clinical_examination_in_musculoskeletal_disease",
            "sports_medicine_and_sports_injuries",
            "the_spine",
            "the_upper_limb",
            "the_hip",
            "the_knee",
            "the_foot_and_ankle",
            "musculoskeletal_tumours",
            "infection_of_the_bones_and_joints",
            "paediatric_orthopaedics",
            "skin_and_subcutaneous_tissue",
            "burns",
            "plastic_and_reconstructive_surgery",
            "cranial_neurosurgery",
            "the_eye_and_orbit",
            "developmental_abnormalities_of_the_face,_mouth_and_jaws:_cleft_lip_and_palate",
            "the_ear,_nose_and_sinuses",
            "the_pharynx,_larynx_and_neck",
            "oral_cavity_cancer",
            "disorders_of_the_salivary_glands",
            "the_thyroid_gland",
            "the_parathyroid_glands",
            "the_adrenal_glands_and_other_abdominal_endocrine_disorders",
            "the_breast",
            "cardiac_surgery",
            "the_thorax",
            "arterial_disorders",
            "venous_disorders",
            "lymphatic_disorders",
            "history_and_examination_of_the_abdomen",
            "the_abdominal_wall,_hernia_and_umbilicus",
            "the_peritoneum,_mesentery,_greater_omentum_and_retroperitoneal_space",
            "the_oesophagus",
            "the_stomach_and_duodenum",
            "bariatric_and_metabolic_surgery",
            "the_liver",
            "the_spleen",
            "the_gallbladder_and_bile_ducts",
            "the_pancreas",
            "functional_disorders_of_the_intestine",
            "the_small_intestine",
            "inflammatory_bowel_disease",
            "the_vermiform_appendix",
            "the_large_intestine",
            "intestinal_obstruction",
            "the_rectum",
            "the_anus_and_anal_canal",
            "urinary_symptoms_and_investigations",
            "the_kidney_and_ureter",
            "the_urinary_bladder",
            "the_prostate_and_seminal_vesicles",
            "the_urethra_and_penis",
            "the_testis_and_scrotum",
            "gynaecology",
            "kidney_transplantation_and_the_principles_of_transplantation",
            "liver_transplantation",
            "pancreas_transplantation",
            "intestinal_and_multivisceral_transplantation",
            "heart_and_lung_transplantation"
        ]        
    },
    "medicine": {
        "marks": 18,
        "topics": [
            "clinical_decision-making",
            "clinical_therapeutics_and_good_prescribing",
            "clinical_genetics",
            "clinical_immunology",
            "population_health_and_epidemiology",
            "principles_of_infectious_disease",
            "poisoning",
            "envenomation",
            "environmental_medicine",
            "acute_medicine_and_critical_illness",
            "infectious_disease",
            "hiv_infection_and_aids",
            "sexually_transmitted_infections",
            "clinical_biochemistry_and_metabolic_medicine",
            "nephrology_and_urology",
            "cardiology",
            "respiratory_medicine",
            "endocrinology",
            "nutritional_factors_in_disease",
            "diabetes_mellitus",
            "gastroenterology",
            "hepatology",
            "haematology_and_transfusion_medicine",
            "rheumatology_and_bone_disease",
            "neurology",
            "stroke_medicine",
            "medical_ophthalmology",
            "medical_psychiatry",
            "dermatology",
            "maternal_medicine",
            "adolescent_and_transition_medicine",
            "ageing_and_disease",
            "oncology",
            "pain_and_palliative_care",
            "laboratory_reference_ranges"
        ]
        
    },
    "radiology": {
        "marks": 7,
        "topics": [
            "x-rays",
            "ct_scan",
            "magnetic_resonance_imaging",
            "ultrasound",
            "thumb_rules",
            "angiography_dsa_interventional_radiology",
            "contrast_agents",
            "gastrointestinal_radiology",
            "hepatobiliary_radiology",
            "pancreatic_radiology",
            "genitourinary_radiology",
            "neuroradiology",
            "musculoskeletal_radiology",
            "women_imaging",
            "cardiovascular_radiology",
            "clinical_essentials",
            "respiratory_radiology",
            "nuclear_medicine",
            "radiotherapy",
            "radiological_anatomy"
        ]
    },
    "emergency_medicine": {
        "marks": 0,
        "topics": [
            "an_approach_of_undifferentiated_patient",
            "basics_of_emergency_medicine",
            "cardiovascular_emergencies",
            "neurological_emergencies",
            "respiratory_emergencies",
            "abdominal_emergencies",
            "miscellaneous_emergencies"
        ]
    },
    "psychiatry": {
        "marks": 7,
        "topics": [
            "organic_mental_disorders",
            "personality_disorders",
            "eating_disorders",
            "sleep_disorders",
            "sexual_disorders",
            "basics_of_psychiatry",
            "schizophrenia_spectrum_and_other_psychotic_disorders",
            "mood_disorders",
            "neurotic_stress_related_and_somatoform_disorders",
            "substance_related_and_addictive_disorders",
            "child_psychiatry",
            "psychoanalysis",
            "mental_health_care_act_2017"
        ]
    },
    "dermatology": {
        "marks": 7,
        "topics": [
            "introduction_to_dermatology",
            "blistering_disorders",
            "pigmentary_disorders",
            "bacterial_infections",
            "fungal_infections",
            "mycobacterial_infections",
            "viral_infections",
            "sexually_transmitted_infections",
            "papulosquamous_disorders",
            "miscellaneous_disorders"
        ]
    },
    "orthopedics": {
        "marks": 10,
        "topics": [
            "bone_and_imaging",
            "bone_and_joint_infections",
            "tuberculosis_of_bone_and_joints",
            "orthopaedics_oncology",
            "nerve_injuries",
            "general_upper_limb_traumatology",
            "spine_pelvis_lower_limb_traumatology",
            "arthritis",
            "metabolic_disorders",
            "sports_injury_and_nm_disorders",
            "pediatric_orthopedics"
        ]
    }
}
